### ISSUE TITLE
World conversion is broken in 7.1 pre1

### ISSUE THREAD

**Issue by JamDoggie** [Joe4422/bta-issues#309]
**Describe the bug**
World conversion from the format used by beta 1.7.3 is currently broken.

**To Reproduce**
1. Run vanilla beta 1.7.3
2. Generate a survival world, maybe place some blocks so you can check back later.
3. Save and quit, and copy the world into your BTA saves folder
4. Try opening the world in BTA, the world will convert

**Expected behavior**
World should convert with no issue, and load all original chunks intact. Chunk borders are expected of course.

**Screenshots**
![image](https://github.com/Better-than-Adventure/bta-issues/assets/17690526/9c056282-7782-4d1f-8703-1a5fd86dfeee)

**Version info:**
 - Version: 7.1pre1

**Additional context**
As an added bonus, ChunkConverter$MappingComplex.getConversion is broken and can cause an additional crash if there are certain blocks in the world. the first line `if (metadata > this.metaIds.length) {` should have a >=, not a >

**Crash Logs**
The error that gets spit out in console is as follows:
`[02:35:30] [Client-Main] java.lang.UnsupportedOperationException
[02:35:30] [Client-Main] 	at net.minecraft.core.world.chunk.reader.ChunkReaderLegacy.getBlocks(ChunkReaderLegacy.java:53)
[02:35:30] [Client-Main] 	at net.minecraft.core.world.chunk.ChunkLoaderLegacy.loadChunkSectionFromCompound(ChunkLoaderLegacy.java:233)
[02:35:30] [Client-Main] 	at net.minecraft.core.world.chunk.ChunkLoaderLegacy.loadChunkIntoWorldFromCompound(ChunkLoaderLegacy.java:197)
[02:35:30] [Client-Main] 	at net.minecraft.core.world.chunk.ChunkLoaderRegion.loadChunk(ChunkLoaderRegion.java:38)
[02:35:30] [Client-Main] 	at net.minecraft.core.world.chunk.ChunkLoaderRegionAsync.loadChunk(ChunkLoaderRegionAsync.java:34)
[02:35:30] [Client-Main] 	at net.minecraft.client.world.chunk.provider.ChunkProviderStatic.func_542_c(ChunkProviderStatic.java:146)
[02:35:30] [Client-Main] 	at net.minecraft.client.world.chunk.provider.ChunkProviderStatic.provideChunk(ChunkProviderStatic.java:107)
[02:35:30] [Client-Main] 	at net.minecraft.core.world.World.getChunkFromChunkCoords(World.java:440)
[02:35:30] [Client-Main] 	at net.minecraft.core.world.chunk.ChunkCache.<init>(ChunkCache.java:30)
[02:35:30] [Client-Main] 	at net.minecraft.client.render.ChunkRenderer.updateRenderer(ChunkRenderer.java:124)
[02:35:30] [Client-Main] 	at net.minecraft.client.render.RenderGlobal.updateRenderers(RenderGlobal.java:982)
[02:35:30] [Client-Main] 	at net.minecraft.client.render.WorldRenderer.renderWorld(WorldRenderer.java:528)
[02:35:30] [Client-Main] 	at net.minecraft.client.render.WorldRenderer.updateCameraAndRender(WorldRenderer.java:418)
[02:35:30] [Client-Main] 	at net.minecraft.client.Minecraft.run(Minecraft.java:681)
[02:35:30] [Client-Main] 	at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by UselessBullets** [comment]
known issue, current work around to do beta to BTA world conversions in 1.7.7.0_02 then copy those worlds to 7.1

**Comment by JamDoggie** [comment]
I see! Good to know. Unfortunately the issue I mentioned in additional context is also still present for certain worlds on that version. I can make a separate issue for it if necessary. I'll also attach a world download that causes this here. 
[https://cdn.discordapp.com/attachments/1212742341329424434/1213026063089930300/world.7z?ex=65f3f98e&is=65e1848e&hm=7236904e75eb9c67a714bb0106376c27658890ab1b8e04d93870b67337f383d9&](url)

**Comment by UselessBullets** [comment]
I'll make sure the specific line of code in the additional context gets fixed as well
